spring:
  profiles: asus
  # postgresql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  # date
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

mybatis:
  config-location:  classpath:mybatis-config.xml

config:
  upload:
    path: D:/temp/dist
    ossPath: D:/temp/osstest
